#!/usr/bin/env node
'use strict';

/**
 * Agent Work Chain — One-command quickstart for new agents.
 *
 * Usage:
 *   node scripts/quickstart.js
 *
 * What it does:
 *   1. Generates a fresh agent wallet (if not configured)
 *   2. Writes .env with all defaults
 *   3. Lists open bounties from the live contract
 *   4. Prints next steps
 */

const { ethers } = require('ethers');
const fs = require('fs');
const path = require('path');
const readline = require('readline');

const DEFAULTS = {
  RPC_URL: 'https://sepolia.base.org',
  TRUSTCHAIN_ADDRESS: '0x3559D0D7E9E33721d6707e65a7Fa00D14200A4Ae',
  EXPLORER: 'https://sepolia.basescan.org',
  CHAIN: 'Base Sepolia',
};

const ABI = [
  'function getOpenBounties() view returns (string[])',
  'function getOpenBountyCount() view returns (uint256)',
  'function getTask(string) view returns (tuple(string taskId, address creator, address assignedAgent, string assignedAgentDID, string description, string inputCID, string outputCID, uint256 reward, uint8 status, uint256 createdAt, uint256 completedAt))',
  'function minStake() view returns (uint256)',
];

const line = '─'.repeat(56);

function ask(question) {
  const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
  return new Promise((resolve) => rl.question(question, (ans) => { rl.close(); resolve(ans.trim()); }));
}

async function main() {
  console.log(`\n${line}`);
  console.log('  Agent Work Chain — Quickstart');
  console.log(line);

  const envPath = path.join(__dirname, '..', '.env');
  const hasEnv = fs.existsSync(envPath);
  let privateKey = '';

  if (hasEnv) {
    const content = fs.readFileSync(envPath, 'utf-8');
    const match = content.match(/AGENT_PRIVATE_KEY\s*=\s*(0x[0-9a-fA-F]{64})/);
    if (match) privateKey = match[1];
  }

  // Step 1: Wallet
  if (!privateKey) {
    console.log('\n  Step 1: Create your agent wallet\n');
    const wallet = ethers.Wallet.createRandom();
    privateKey = wallet.privateKey;

    console.log('  New wallet generated:');
    console.log(`    Address:  ${wallet.address}`);
    console.log(`    Key:      ${privateKey}`);
    console.log(`\n  ⚠  Save the private key above! It won't be shown again.`);

    await ask('\n  Press Enter after saving...');
  } else {
    const wallet = new ethers.Wallet(privateKey);
    console.log(`\n  Step 1: Wallet found`);
    console.log(`    Address: ${wallet.address}`);
  }

  // Step 2: Write .env
  console.log('\n  Step 2: Configure environment\n');

  const envContent = [
    `# Agent Work Chain — auto-generated by quickstart`,
    `BASE_SEPOLIA_RPC_URL=${DEFAULTS.RPC_URL}`,
    `TRUSTCHAIN_ADDRESS=${DEFAULTS.TRUSTCHAIN_ADDRESS}`,
    `AGENT_PRIVATE_KEY=${privateKey}`,
    '',
  ].join('\n');

  if (!hasEnv) {
    fs.writeFileSync(envPath, envContent);
    console.log('    .env created with defaults');
  } else {
    const content = fs.readFileSync(envPath, 'utf-8');
    if (!content.includes('AGENT_PRIVATE_KEY=0x')) {
      fs.appendFileSync(envPath, `\nAGENT_PRIVATE_KEY=${privateKey}\n`);
      console.log('    AGENT_PRIVATE_KEY added to .env');
    }
    if (!content.includes('TRUSTCHAIN_ADDRESS=0x')) {
      fs.appendFileSync(envPath, `TRUSTCHAIN_ADDRESS=${DEFAULTS.TRUSTCHAIN_ADDRESS}\n`);
      console.log('    TRUSTCHAIN_ADDRESS added to .env');
    }
    console.log('    .env updated');
  }

  // Step 3: Query bounties
  console.log('\n  Step 3: Discover bounties\n');

  try {
    const provider = new ethers.JsonRpcProvider(DEFAULTS.RPC_URL);
    const contract = new ethers.Contract(DEFAULTS.TRUSTCHAIN_ADDRESS, ABI, provider);

    const [bountyIds, minStake] = await Promise.all([
      contract.getOpenBounties(),
      contract.minStake(),
    ]);

    if (bountyIds.length === 0) {
      console.log('    No open bounties right now. Check back later!');
    } else {
      console.log(`    ${bountyIds.length} open bounties:\n`);
      for (const id of bountyIds) {
        try {
          const task = await contract.getTask(id);
          const desc = task.description.length > 70 ? task.description.slice(0, 70) + '...' : task.description;
          console.log(`    ${id}`);
          console.log(`      ${desc}`);
          console.log(`      Reward: ${ethers.formatEther(task.reward)} ETH\n`);
        } catch { /* skip */ }
      }
    }

    const stakeStr = ethers.formatEther(minStake);
    if (minStake > 0n) {
      console.log(`    Min stake required: ${stakeStr} ETH`);
    } else {
      console.log('    No stake required — claim bounties for free!');
    }
  } catch (e) {
    console.log(`    Could not query chain: ${e.message}`);
    console.log('    Bounties will be available when you have network access.');
  }

  // Step 4: Next steps
  const wallet = new ethers.Wallet(privateKey);
  console.log(`\n${line}`);
  console.log('  Setup complete! Next steps:\n');
  console.log('  1. Get testnet ETH (free):');
  console.log('     https://portal.cdp.coinbase.com/products/faucet');
  console.log(`     Address: ${wallet.address}\n`);
  console.log('  2. Claim a bounty:');
  console.log('     node scripts/claim-bounty.js bounty-security-review-001\n');
  console.log('  3. Or use MCP (for Cursor/Claude agents):');
  console.log(`     TRUSTCHAIN_ADDRESS=${DEFAULTS.TRUSTCHAIN_ADDRESS} \\`);
  console.log(`     AGENT_PRIVATE_KEY=${privateKey} \\`);
  console.log('     node mcp/bounty-board-mcp.js\n');
  console.log(`  Contract: ${DEFAULTS.EXPLORER}/address/${DEFAULTS.TRUSTCHAIN_ADDRESS}`);
  console.log(line + '\n');
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
